name: Cross-Compile Qt6.8 App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Qt 6.8
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.*'
          modules: 'qtbase qttools'
          cache: true

      - name: Configure CMake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
        shell: bash

      - name: Build
        run: |
          cmake --build build --config Release
        shell: bash

      - name: Package Windows (windeployqt)
        if: matrix.os == 'windows-latest'
        run: |
          windeployqt --release build/MyQtApp.exe
        shell: bash

      - name: Package Linux (linuxdeployqt)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install -y patchelf
          linuxdeployqt build/MyQtApp -appimage
        shell: bash

      - name: Package macOS (macdeployqt)
        if: matrix.os == 'macos-latest'
        run: |
          macdeployqt build/MyQtApp.app
        shell: bash

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: build/
